### ISSUE TITLE
request for status failed: Error: HTTPError: Response code 400 (Bad Request)

### ISSUE THREAD

**Issue by Leo1907** [peterwoj/homebridge-blynk-platform#12]
Hi, 
I try to add a digital pin 14 like a button. 
the Blynk api url look like this : http://45.55.96.146/token/get/14 
Blynk server respond "Wrong pin format."
The right digital pin name need 'D' like this:  http://45.55.96.146/token/get/D14 
Is any config on add-in setting can change the pin name to make it has 'D'
Thanks,

**Comment by peterwoj** [comment]
Thanks for the detail, I completely left of the type of pin from the request.
