### ISSUE TITLE
Accessory types

### ISSUE THREAD

**Issue by Cr4ck3r32** [peterwoj/homebridge-blynk-platform#14]
Hello, 

I am using Blynk and I would like to know why in HomeKit it only identifies buttons / switches, regardless of the type of accessory that I put on it. Is there a way that I can identify temperature sensors or other things?

Thank you and have a nice day.

**Comment by peterwoj** [comment]
It's the only thing that I have implemented right now.  I haven't added more functionality outside of these controls.  Is there anything in particular which would be wanted first?

**Comment by Cr4ck3r32** [comment]
Hello, i am using this plugin with Blynk and Homekit, but in Blynk we are using a "Button" a "Labeled Value" and a "Slider" so i would like that these 3 things to be interpreted in Homekit, because we are using the "BUtton - switch a plug On/Off" the "Labeled Value - show how much Watt we are consuming" and the "Slider - to give more or less power on the plug". So it would be very nice to have that in the plugin to be showed in Homekit.

**Comment by moschu** [comment]
Hey,
I love your plugin, but I miss a solution to read temperature for a nice automation. Is it possible for you to implement a temperature accessory? It would be very nice!

**Comment by damjangr** [comment]
Great plugin.
I would also like to add a solution for reading temperature, humidity, air pressure, etc.
Thanks

**Comment by peterwoj** [comment]
Added several types that I could quickly test and corrected a handful of additional bugs I found
