### ISSUE TITLE
blynk-cloud: Hangs after first request

### ISSUE THREAD

**Issue by WTPGaming** [peterwoj/homebridge-blynk-platform#19]
Fresh install of both homebridge and homebridge-blynk-platform...

Issue:
After everything is paired and my device is connected to homebridge, i go to turn on my first accessory, and it send the update command with the value of 0 or 1 respectively (http://blynk-cloud.com/xxxxxxx/update/D5?value=0), but following that homebridge freezes, the ui continues to update and everything works but it seems that homekit-blynk-platform just freezes, the logs show nothing out of the ordinary (actually they show nothing at all)

Steps to reproduce:
1. sudo npm i -g homekit
2. sudo npm i -g homebridge-config-ui-x
3. sudo npm i -g homebridge-blynk-platform
4. cd ~/
5. mkdir .homebridge
6. sudo nano config.json
7. paste
`{
    "mdns": {
        "interface": "192.168.1.21"
    },
    "bridge": {
        "name": "Homebridge",
        "username": "C8:D7:19:C5:45:4B",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "This is an example configuration file. You can use this as a template for creating your own configuration file.",
    "platforms": [
        {
            "platform": "config",
            "name": "Config",
            "port": 8080,
            "sudo": true,
            "restart": "sudo -n systemctl restart homebridge",
            "log": {
                "method": "systemd",
                "service": "homebridge"
            }
        },
        {
            "platform": "BlynkPlatform",
            "serverurl": "http://blynk-cloud.com",
            "pollerseconds": 1,
            "devices": [
                {
                    "manufacturer": "WTPGaming",
                    "name": "DeskLights",
                    "token": "xxxxxxxxxx",
                    "deviceId": "31225",
                    "discover": true
                },
                {
                    "manufacturer": "WTPGaming",
                    "name": "DeskLightsThing",
                    "token": "xxxxxxxxxx",
                    "deviceId": "112233",
                    "discover": false,
                    "accessories": [
                        {
                            "model": "DeskLight",
                            "name": "DeskLightWarm",
                            "pintype": "DIGITAL",
                            "pinnumber": "D4",
                            "type": "BUTTON"
                        },
                        {
                            "model": "DeskLight",
                            "name": "DeskLightCold",
                            "pintype": "DIGITAL",
                            "pinnumber": "D5",
                            "type": "BUTTON"
                        }
                    ]
                }
            ]
        }
    ],
    "accessories": []
}`
9. homebridge
10. in windows (because lack of permission) copy 'C:\Users\{USER}\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\home\austin\.homebridge' into 'C:\Users\{USER}\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\root'
11. sudo homebridge -I
12. add the homebridge accessory to the home app of my iPhone X (iOS 13.5 jailbroken)
13. click on the added accessory

Please help me! I'm a big fan of all the work you've done here and I've given you a star!!! thanks for your consideration!!!

**Comment by peterwoj** [comment]
Looks like the rest api is going away, closing this
