### ISSUE TITLE
Name and room of accessory resets to default

### ISSUE THREAD

**Issue by vivekanandbv** [peterwoj/homebridge-blynk-platform#37]
Accessory doesn't display name set in the plugin config. It has to be changed in home app, and quite frequently resets to the default "worsted button" name. Probably an issue with the cache? please look into it.

**Comment by peterwoj** [comment]
Haven't seen the name change for a configured item.  If for some reason the accessory cache is refreshed there can be room changes.  What version of the plugin and what's your config look like?

**Comment by vivekanandbv** [comment]
Config:
{

"platform": "BlynkPlatform",

"serverurl": "http://188.166.206.43", "pollerseconds": 1,

"devices": [

{

"name": "Door Lock",

"token": "VYbnqVmXFIZZxLDPFHPX1YWOWJsGOYK3",

"deviceId": 0,

"manufacturer": "Vivek",

"discover": true,

"accessories": [

{

"model": "NodeMCU",

"name": "Door Lock",

"pintype": "VIRTUAL",

"pinnumber": 1,

"type": "BUTTON"
}
]
}
]
}

**Comment by vivekanandbv** [comment]
Config: 

Config:
{

"platform": "BlynkPlatform",

"serverurl": "http://xxxxxxxxxx", "pollerseconds": 1,

"devices": [

{

"name": "Door Lock",

"token": "VYbnqVmXFIZZxLDPFHPX1YWOWJsGOYK3",

"deviceId": 0,

"manufacturer": "Vivek",

"discover": true,

"accessories": [

{

"model": "NodeMCU",

"name": "Door Lock",

"pintype": "VIRTUAL",

"pinnumber": 1,

"type": "BUTTON"
}
]
}
]
}

**Comment by vivekanandbv** [comment]
Config:
{

"platform": "BlynkPlatform",

"serverurl": "http://xxxxxxxxxx", "pollerseconds": 1,

"devices": [

{

"name": "Door Lock",

"token": "XXXXXXXX",

"deviceId": 0,

"manufacturer": "Vivek",

"discover": true,

"accessories": [

{

"model": "NodeMCU",

"name": "Door Lock",

"pintype": "VIRTUAL",

"pinnumber": 1,

"type": "BUTTON"
}
]
}
]
}

**Comment by vivekanandbv** [comment]
Also, the ‘type of’ drop down menu does not have a switch option in it.

**Comment by peterwoj** [comment]
With discover set to true the name should come from what is defined in the blynk-server control itself.  Is there anything that comes out of logs that references removing adding/removing accessories

**Comment by vivekanandbv** [comment]
Ah, ok. I didn’t know you had to name the button in the blynk app. I thought naming the accessory in the plug-in would do it. My bad. It works now.
